apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: odoo-postgres
  name: odoo-postgres
  namespace: tp-odoo
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: odoo-postgres
  type: ClusterIP
status:
  loadBalancer: {}
