apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: odoo-postgres
  name: odoo-postgres
  namespace: tp-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odoo-postgres
    spec:
      containers:
      - image: postgres:13
        name: postgres
        ports:
        - containerPort: 5432
        env:
             - name: POSTGRES_DB
               value: postgres
             - name: POSTGRES_USER
               value: odoo
             - name: POSTGRES_PASSWORD
               valueFrom:
                  secretKeyRef:
                     name: odoo-pgsql-password
                     key: odoo
        volumeMounts:
              - name: pgsql-persistent-storage
                mountPath: /var/lib/postgresql
        resources: {}
      volumes:
         - name: pgsql-persistent-storage
           persistentVolumeClaim:
                 claimName: data-postgres-claim
status: {}
