apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: odoo-web
  name: odoo-web
  namespace: tp-odoo
spec:
  ports:
  - port: 25000
    protocol: TCP
    targetPort: 8069
    nodePort: 31000
  selector:
    app: odoo-web
  type: NodePort
status:
  loadBalancer: {}
